CREATE TABLE `zen_male` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(32) DEFAULT NULL COMMENT '姓名',
  `gender` varchar(10) DEFAULT NULL COMMENT '性别',
  `job` varchar(32) DEFAULT NULL,
  `hobby` varchar(64) DEFAULT NULL,
  `fname` varchar(32) DEFAULT NULL COMMENT '法名',
  `birthday` varchar(32) DEFAULT NULL,
  `personnel_id` varchar(32) DEFAULT NULL,
  `phone_num` varchar(20) DEFAULT NULL COMMENT '手机号',
  `race` varchar(20) DEFAULT NULL,
  `degree` varchar(32) DEFAULT NULL,
  `health` varchar(32) DEFAULT NULL,
  `telephone_num` varchar(20) DEFAULT NULL,
  `edit_time` varchar(32) DEFAULT NULL,
  `receipt` varchar(32) DEFAULT NULL COMMENT '收据',
  `workplace` varchar(64) DEFAULT NULL,
  `province` varchar(64) DEFAULT NULL,
  `city` varchar(64) DEFAULT NULL,
  `district` varchar(64) DEFAULT NULL,
  `address` varchar(64) DEFAULT NULL,
  `postcode` varchar(64) DEFAULT NULL,
  `graduate_time` varchar(32) DEFAULT NULL,
  `graduate_school` varchar(64) DEFAULT NULL,
  `first_job_entry_time` varchar(64) DEFAULT NULL,
  `first_job_workplace` varchar(64) DEFAULT NULL,
  `second_job_entry_time` varchar(32) DEFAULT NULL,
  `second_job_workplace` varchar(64) DEFAULT NULL,
  `retirement_date` varchar(32) DEFAULT NULL,
  `retirement_workplace` varchar(64) DEFAULT NULL,
  `year2start_learning_buddhism` varchar(32) DEFAULT NULL,
  `years_of_learning_buddhism` varchar(10) DEFAULT NULL,
  `deep_understanding_of_dharma` varchar(64) DEFAULT NULL,
  `reason2learning_dharma` varchar(128) DEFAULT NULL,
  `nums_of_buddhism_book` varchar(10) DEFAULT NULL,
  `easy2learn_buddhism_book` varchar(128) DEFAULT NULL,
  `hard2read` varchar(128) DEFAULT NULL,
  `maxim` varchar(128) DEFAULT NULL,
  `buddhist_disciples_of_family` varchar(128) DEFAULT NULL,
  `editor` varchar(128) DEFAULT NULL,
  `others` varchar(128) DEFAULT NULL,
  `learn_dharma_kinds` varchar(64) DEFAULT NULL,
  `learn_dharma_address` varchar(128) DEFAULT NULL,
  `code` varchar(64) DEFAULT NULL COMMENT '皈依证号',
  `if_apply_learn_place` varchar(10) DEFAULT '否',
  `notes` varchar(128) DEFAULT NULL,
  `mark` tinyint(1) NOT NULL DEFAULT '0',
  `ipaddress` varchar(32) DEFAULT NULL,
  `comes` tinyint(4) NOT NULL DEFAULT '0' COMMENT '来自手机或者笔记本录入, 0: 笔记本, 1: 手机',
  PRIMARY KEY (`id`),
  UNIQUE KEY `code` (`code`)
) ENGINE=InnoDB AUTO_INCREMENT=9 DEFAULT CHARSET=utf8;
